'use client';

import { useState } from 'react';

export default function CVRedoPage() {
  const [isPro, setIsPro] = useState(false); // In a real app, this would come from user authentication
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [resultData, setResultData] = useState<any>(null);
  const [parsingProgress, setParsingProgress] = useState(0);
  const [parsingStep, setParsingStep] = useState('');

  const handleDownload = () => {
    const data = resultData?.parsedData || {};
    const cvContent = `═══════════════════════════════════════════
              ${data.name || 'JOHN DOE'}
        ${data.title || 'Software Developer'}
═══════════════════════════════════════════

📧 ${data.email || 'john@example.com'}          📱 ${data.phone || '+1 (555) 123-4567'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROFESSIONAL SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Experienced software developer with ${data.experience || '5+ years'} of expertise in web technologies
and team leadership. Passionate about creating efficient, scalable solutions
with modern design principles and user-centered approaches.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXPERIENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Senior Developer
Tech Corp | 2020 - Present
• Developed and maintained web applications using React & Node.js
• Led a team of 5 developers on multiple high-impact projects
• Implemented CI/CD pipelines improving deployment efficiency by 40%
• Collaborated with cross-functional teams to deliver products on time

Junior Developer
Startup Inc | 2018 - 2020
• Built responsive web applications with modern JavaScript frameworks
• Collaborated with design team on user experience improvements
• Participated in code reviews and mentored junior developers

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKILLS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Programming: ${data.skills?.slice(0, 3).join(', ') || 'JavaScript, TypeScript, Python'}
• Frameworks: React, Node.js, Express, Django
• Databases: SQL, MongoDB, PostgreSQL
• Tools: Git, Docker, AWS, Jenkins
• Design: Figma, Adobe Creative Suite, UI/UX Principles
• Soft Skills: Team Leadership, Problem Solving, Communication

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDUCATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${data.education || 'Bachelor of Computer Science'}
University of Technology | 2018
• GPA: 3.8/4.0
• Relevant Coursework: Data Structures, Algorithms, Web Development

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DESIGN IMPROVEMENTS APPLIED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Applied modern ${data.template || 'Creative'} template with gradient elements
• Enhanced visual hierarchy with contemporary typography
• Added color accents and professional spacing
• Optimized content layout for better readability
• Incorporated modern design elements and icons
• Improved section organization and flow
• Enhanced mobile responsiveness
• Design Quality Score: ${resultData?.accuracy || 96}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Vellon 2.0 CV Redo - Free Version
Upgrade to Pro for premium templates and advanced customization!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    const blob = new Blob([cvContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'redesigned-cv.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setShowResult(false);
    setParsingProgress(0);

    // Get form data and file
    const formData = new FormData(e.target as HTMLFormElement);
    const file = formData.get('resume') as File;
    const selectedTemplate = formData.get('template') as string;

    if (!file) {
      alert('Please select a CV file to upload.');
      setIsSubmitting(false);
      return;
    }

    // File type validation
    const allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
    if (!allowedTypes.includes(file.type)) {
      alert('Please upload a PDF, DOC, or DOCX file.');
      setIsSubmitting(false);
      return;
    }

    // File size validation (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      alert('File size must be less than 10MB.');
      setIsSubmitting(false);
      return;
    }

    // File property analysis simulation (frontend limitation: cannot parse PDF content)
    const parsingSteps = [
      `Validating ${file.name} (${(file.size / 1024).toFixed(0)}KB file)...`,
      'Analyzing filename for profession keywords...',
      'Extracting potential name from file naming patterns...',
      'Estimating experience level from file size...',
      'Mapping profession to relevant skills database...',
      `Applying ${selectedTemplate} design template...`,
      'Optimizing layout and typography...',
      'Enhancing visual hierarchy...',
      'Preparing downloadable redesigned CV...',
      'Finalizing design elements...'
    ];

    for (let i = 0; i < parsingSteps.length; i++) {
      setParsingStep(parsingSteps[i]);
      setParsingProgress(((i + 1) / parsingSteps.length) * 100);
      await new Promise(resolve => setTimeout(resolve, 500));
    }

    setIsSubmitting(false);

    // Simulate parsing based on actual file properties
    const fileName = file.name.toLowerCase();
    const fileSize = file.size;

    // Advanced parsing logic based on file analysis
    const analyzeFileName = (fileName: string) => {
      const lowerName = fileName.toLowerCase();

      // Profession detection with priority
      if (lowerName.includes('software') || lowerName.includes('developer') || lowerName.includes('engineer') || lowerName.includes('programmer')) {
        return {
          profession: 'Software Developer',
          skills: ['JavaScript', 'React', 'Node.js', 'Python', 'UI/UX', 'Figma', 'Adobe Creative Suite']
        };
      }
      if (lowerName.includes('designer') || lowerName.includes('ux') || lowerName.includes('ui')) {
        return {
          profession: 'UX/UI Designer',
          skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research', 'Wireframing', 'Usability Testing']
        };
      }
      if (lowerName.includes('manager') || lowerName.includes('lead') || lowerName.includes('director')) {
        return {
          profession: 'Project Manager',
          skills: ['Project Management', 'Agile', 'Scrum', 'Leadership', 'Communication', 'Risk Management']
        };
      }
      if (lowerName.includes('analyst') || lowerName.includes('data')) {
        return {
          profession: 'Data Analyst',
          skills: ['SQL', 'Python', 'Excel', 'Tableau', 'Power BI', 'Statistics', 'Data Visualization']
        };
      }
      if (lowerName.includes('marketing') || lowerName.includes('market')) {
        return {
          profession: 'Marketing Specialist',
          skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Google Analytics', 'Email Marketing']
        };
      }

      // Default professional profile
      return {
        profession: 'Professional',
        skills: ['Communication', 'Leadership', 'Problem Solving', 'Team Collaboration', 'Project Management']
      };
    };

    const professionData = analyzeFileName(fileName);

    // Experience level based on file size and naming patterns
    const getExperienceLevel = (fileSize: number, fileName: string) => {
      const lowerName = fileName.toLowerCase();
      if (lowerName.includes('senior') || lowerName.includes('lead') || lowerName.includes('principal')) return '7+ years';
      if (lowerName.includes('mid') || fileSize > 600000) return '4-6 years';
      if (fileSize > 400000) return '3-5 years';
      if (fileSize > 200000) return '2-4 years';
      return '1-3 years';
    };

    // Enhanced name extraction with better patterns
    const extractNameFromFile = (fileName: string) => {
      // Remove extension and common CV words
      let cleanName = fileName
        .replace(/\.(pdf|doc|docx)$/i, '')
        .replace(/\b(cv|resume|curriculum| vitae)\b/gi, '')
        .replace(/[_-]/g, ' ')
        .trim();

      // Handle different naming patterns
      if (cleanName.includes(' ')) {
        // Already has spaces, assume it's "First Last"
        return cleanName.split(' ').slice(0, 2).map(word =>
          word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
        ).join(' ');
      } else if (cleanName.length > 6) {
        // Single word, try to split camelCase or find name-like patterns
        const camelCaseMatch = cleanName.match(/([a-z]+)([A-Z][a-z]+)/);
        if (camelCaseMatch) {
          return `${camelCaseMatch[1].charAt(0).toUpperCase()}${camelCaseMatch[1].slice(1)} ${camelCaseMatch[2]}`;
        }
      }

      // Fallback to generic name
      return 'Alex Johnson';
    };

    // Generate template-specific improvements
    const templateImprovements = {
      'Classic Professional': [
        'Applied clean, traditional design with serif typography',
        'Used professional color scheme (navy and gray)',
        'Enhanced readability with optimal line spacing',
        'Added subtle borders and dividers for Classic Professional template'
      ],
      'Modern Clean': [
        'Applied minimalist design with sans-serif fonts',
        'Used modern color palette with accent colors',
        'Optimized whitespace and visual hierarchy',
        'Added contemporary layout elements for Modern Clean template'
      ],
      'Minimalist': [
        'Applied ultra-clean design with maximum whitespace',
        'Used monochromatic color scheme',
        'Focused on typography and content hierarchy',
        'Removed visual clutter for maximum impact in Minimalist template'
      ]
    };

    const extractedData = {
      name: extractNameFromFile(fileName),
      title: professionData.profession,
      email: `${extractNameFromFile(fileName).toLowerCase().replace(/\s+/g, '.')}@email.com`,
      phone: '+1 (555) 123-4567',
      experience: getExperienceLevel(fileSize, fileName),
      skills: professionData.skills,
      education: professionData.profession.includes('Software') ? 'Bachelor of Computer Science' :
                 professionData.profession.includes('Design') ? 'Bachelor of Fine Arts' :
                 professionData.profession.includes('Data') ? 'Bachelor of Statistics' :
                 'Bachelor of Business Administration',
      template: selectedTemplate
    };

    setResultData({
      template: `${selectedTemplate} Template`,
      improvements: [
        `Analyzed ${file.name} (${(file.size / 1024).toFixed(0)}KB)`,
        ...templateImprovements[selectedTemplate as keyof typeof templateImprovements],
        'Enhanced visual hierarchy with modern typography',
        'Optimized content layout for better readability',
        'Added professional design elements'
      ],
      parsedData: extractedData,
      accuracy: Math.floor(88 + Math.random() * 8), // 88-96% accuracy
      fileInfo: {
        name: file.name,
        size: file.size,
        type: file.type,
        selectedTemplate: selectedTemplate
      },
      downloadUrl: '#'
    });
    setShowResult(true);
  };

  if (!isPro) {
    return (
      <div className="bg-zinc-50 dark:bg-black">
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <section className="text-center py-20 sm:py-32">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white mb-6">
              CV Redo
            </h1>
            <p className="max-w-3xl mx-auto text-xl text-gray-600 dark:text-gray-300 mb-8">
              Redesign your CV with basic templates and layouts for free.
            </p>
          </section>

          <section className="py-16 sm:py-24">
            <div className="max-w-3xl mx-auto">
              <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
                <div className="mb-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                  <p className="text-blue-800 dark:text-blue-200 text-sm">
                    <strong>Free Plan:</strong> Basic templates with standard layouts. Upgrade to Pro for premium templates and advanced customization.
                  </p>
                  <p className="text-blue-700 dark:text-blue-300 text-xs mt-2">
                    <em>Note: This demo analyzes file properties and simulates parsing. Real PDF content parsing requires server-side processing.</em>
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                  <div>
                    <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Full Name
                    </label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="John Doe"
                    />
                  </div>
                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Email
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="john@example.com"
                    />
                  </div>
                  <div>
                    <label htmlFor="resume" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Upload Your CV
                    </label>
                    <input
                      type="file"
                      id="resume"
                      name="resume"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      accept=".pdf,.doc,.docx"
                    />
                  </div>
                  <div>
                    <label htmlFor="template" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Choose Template
                    </label>
                    <select
                      id="template"
                      name="template"
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    >
                      <option value="classic">Classic Professional</option>
                      <option value="modern">Modern Clean</option>
                      <option value="minimal">Minimalist</option>
                    </select>
                  </div>
                  {isSubmitting && (
                    <div className="mb-4 p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-purple-800 dark:text-purple-200">
                          {parsingStep}
                        </span>
                        <span className="text-sm text-purple-600 dark:text-purple-300">
                          {Math.round(parsingProgress)}%
                        </span>
                      </div>
                      <div className="w-full bg-purple-200 dark:bg-purple-800 rounded-full h-2">
                        <div
                          className="bg-purple-600 dark:bg-purple-400 h-2 rounded-full transition-all duration-300"
                          style={{ width: `${parsingProgress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-black dark:bg-white text-white dark:text-black py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isSubmitting ? 'Redesigning Your CV...' : 'Redo My CV (Free)'}
                  </button>
                </form>

                {showResult && resultData && (
                  <div className="mt-8 bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 border border-gray-200 dark:border-gray-700">
                    <div className="text-center mb-6">
                      <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 dark:bg-green-900/20 rounded-full mb-4">
                        <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                      </div>
                      <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">CV Redesign Complete!</h3>
                      <p className="text-gray-600 dark:text-gray-300">Your CV has been redesigned with a modern template</p>
                    </div>

                    <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 mb-6">
                      <h4 className="font-semibold text-gray-900 dark:text-white mb-3">Template: {resultData.template}</h4>
                      <div className="aspect-[3/4] bg-gradient-to-br from-purple-50 via-pink-50 to-indigo-100 dark:from-gray-800 dark:via-purple-900/20 dark:to-indigo-900/20 rounded-xl border border-purple-200 dark:border-purple-600 p-6 mb-4 overflow-hidden shadow-lg">
                        <div className="text-gray-900 dark:text-white">
                          {/* Modern Header */}
                          <div className="relative mb-6">
                            <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg opacity-10"></div>
                            <div className="relative text-center py-4">
                              <h3 className="font-bold text-xl text-purple-900 dark:text-purple-200 mb-1">
                                {resultData.parsedData?.name || 'JOHN DOE'}
                              </h3>
                              <p className="text-purple-700 dark:text-purple-300 font-medium text-sm">
                                {resultData.parsedData?.title || 'Software Developer'}
                              </p>
                              <div className="flex justify-center mt-2">
                                <div className="w-12 h-1 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full"></div>
                              </div>
                            </div>
                          </div>

                          {/* Contact Section */}
                          <div className="mb-5">
                            <div className="flex items-center gap-2 mb-3">
                              <div className="w-3 h-3 bg-purple-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-purple-800 dark:text-purple-300 uppercase tracking-wide">Contact</h4>
                            </div>
                            <div className="ml-5 space-y-2">
                              <div className="flex items-center gap-2">
                                <span className="text-purple-600 dark:text-purple-400">✉</span>
                                <p className="text-gray-700 dark:text-gray-200 text-sm">john@example.com</p>
                              </div>
                              <div className="flex items-center gap-2">
                                <span className="text-purple-600 dark:text-purple-400">📱</span>
                                <p className="text-gray-700 dark:text-gray-200 text-sm">+1 (555) 123-4567</p>
                              </div>
                            </div>
                          </div>

                          {/* Experience Section */}
                          <div className="mb-5">
                            <div className="flex items-center gap-2 mb-3">
                              <div className="w-3 h-3 bg-pink-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-pink-800 dark:text-pink-300 uppercase tracking-wide">Experience</h4>
                            </div>
                            <div className="ml-5">
                              <div className="mb-3">
                                <p className="font-semibold text-sm text-gray-900 dark:text-white">Senior Developer</p>
                                <p className="text-pink-600 dark:text-pink-400 text-xs font-medium">Tech Corp • 2020-Present</p>
                                <ul className="text-gray-700 dark:text-gray-200 text-xs mt-2 space-y-1">
                                  <li className="flex items-start gap-2">
                                    <span className="text-pink-500 mt-1">•</span>
                                    <span>Developed modern web applications using React & Node.js</span>
                                  </li>
                                  <li className="flex items-start gap-2">
                                    <span className="text-pink-500 mt-1">•</span>
                                    <span>Led cross-functional development teams</span>
                                  </li>
                                </ul>
                              </div>
                            </div>
                          </div>

                          {/* Skills Section */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-3">
                              <div className="w-3 h-3 bg-indigo-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-indigo-800 dark:text-indigo-300 uppercase tracking-wide">Skills</h4>
                            </div>
                            <div className="ml-5 flex flex-wrap gap-2">
                              {(resultData.parsedData?.skills || ['JavaScript', 'React', 'Node.js', 'Python', 'UI/UX']).map((skill: string, index: number) => (
                                <span key={index} className="bg-gradient-to-r from-indigo-100 to-purple-100 dark:from-indigo-900/40 dark:to-purple-900/40 text-indigo-800 dark:text-indigo-200 text-xs px-3 py-1 rounded-full border border-indigo-200 dark:border-indigo-600">
                                  {skill}
                                </span>
                              ))}
                            </div>
                          </div>

                          {/* Design Quality Indicator */}
                          <div className="mt-4 p-3 bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 rounded-lg border border-green-200 dark:border-green-700">
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-xs font-medium text-green-800 dark:text-green-200">Design Quality</span>
                              <span className="text-xs font-bold text-green-800 dark:text-green-200">98%</span>
                            </div>
                            <div className="w-full bg-green-200 dark:bg-green-800 rounded-full h-1.5">
                              <div className="bg-gradient-to-r from-green-500 to-emerald-500 h-1.5 rounded-full" style={{ width: '98%' }}></div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <h5 className="font-medium text-gray-900 dark:text-white">File analyzed:</h5>
                        <p className="text-sm text-gray-600 dark:text-gray-300">
                          {resultData.fileInfo?.name} ({(resultData.fileInfo?.size / 1024).toFixed(0)}KB) • {resultData.fileInfo?.selectedTemplate} template
                        </p>
                        <h5 className="font-medium text-gray-900 dark:text-white mt-3">Improvements made:</h5>
                        <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                          {resultData.improvements.map((improvement: string, index: number) => (
                            <li key={index} className="flex items-center">
                              <span className="text-green-500 mr-2">✓</span>
                              {improvement}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex gap-3">
                        <button
                          onClick={handleDownload}
                          className="flex-1 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-medium py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors"
                        >
                          Download Free Version
                        </button>
                        <a
                          href="/pricing"
                          className="flex-1 bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-medium py-3 px-4 rounded-lg border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-center"
                        >
                          Upgrade to Pro
                        </a>
                      </div>

                      <div className="text-center">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Pro version includes premium templates, custom color schemes, and advanced customization options
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                <div className="mt-8 p-6 bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-700 rounded-lg">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">Upgrade to Pro for:</h3>
                  <ul className="text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                    <li>✓ 20+ premium templates</li>
                    <li>✓ Custom color schemes</li>
                    <li>✓ Advanced font options</li>
                    <li>✓ Multiple layout variations</li>
                    <li>✓ Export in all formats</li>
                  </ul>
                  <a
                    href="/pricing"
                    className="inline-block bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-medium py-2 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors text-sm"
                  >
                    Upgrade to Pro - $9.99/month
                  </a>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    );
  }

  // Pro user interface would go here
  return (
    <div className="bg-zinc-50 dark:bg-black">
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <section className="text-center py-20 sm:py-32">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white mb-6">
            CV Redo Pro
          </h1>
          <p className="max-w-3xl mx-auto text-xl text-gray-600 dark:text-gray-300 mb-8">
            Professional CV redesign with premium templates and advanced customization.
          </p>
        </section>

        <section className="py-16 sm:py-24">
          <div className="max-w-3xl mx-auto">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
              <div className="mb-6 p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
                <p className="text-green-800 dark:text-green-200 text-sm font-medium">
                  ✓ Pro Plan Active - Full access to premium templates
                </p>
              </div>

              <form className="space-y-6">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Full Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    placeholder="John Doe"
                  />
                </div>
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    placeholder="john@example.com"
                  />
                </div>
                <div>
                  <label htmlFor="resume" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Upload Your CV
                  </label>
                  <input
                    type="file"
                    id="resume"
                    name="resume"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    accept=".pdf,.doc,.docx"
                  />
                </div>
                <div>
                  <label htmlFor="template" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Choose Premium Template
                  </label>
                  <select
                    id="template"
                    name="template"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                  >
                    <option value="executive">Executive Suite</option>
                    <option value="creative">Creative Professional</option>
                    <option value="tech">Tech Innovator</option>
                    <option value="academic">Academic Excellence</option>
                    <option value="startup">Startup Founder</option>
                  </select>
                </div>
                <div>
                  <label htmlFor="colorScheme" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Color Scheme
                  </label>
                  <select
                    id="colorScheme"
                    name="colorScheme"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                  >
                    <option value="blue">Professional Blue</option>
                    <option value="green">Modern Green</option>
                    <option value="purple">Creative Purple</option>
                    <option value="gray">Minimal Gray</option>
                  </select>
                </div>
                <button
                  type="submit"
                  className="w-full bg-black dark:bg-white text-white dark:text-black py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors font-medium"
                >
                  Redo My CV (Pro)
                </button>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}