import { NextRequest, NextResponse } from 'next/server';
import puppeteer from 'puppeteer';

// Import themes statically to avoid dynamic require issues with Turbopack
const flatTheme = require('jsonresume-theme-flat') as any;
const paperTheme = require('jsonresume-theme-paper') as any;
const elegantTheme = require('jsonresume-theme-elegant') as any;
const kendallTheme = require('jsonresume-theme-kendall') as any;

const themeMap: { [key: string]: any } = {
  'flat': flatTheme,
  'paper': paperTheme,
  'elegant': elegantTheme,
  'kendall': kendallTheme,
};

export async function POST(request: NextRequest) {
  try {
    const { data, templateId, isPro, type, roadmap } = await request.json();

    let html = '';

    if (type === 'roadmap' && roadmap) {
      // Generate HTML for career roadmap
      html = generateRoadmapHTML(roadmap);
    } else {
      // CV generation
      // For now, map templateId to a default theme. Full integration with Reactive Resume templates requires more setup.
      const defaultTheme = 'flat';
      const themePackage = themeMap[defaultTheme];
      if (!themePackage) {
        return NextResponse.json({ error: 'Theme not found' }, { status: 400 });
      }

      const theme = require(themePackage) as any;
      html = theme.render(data);
    }

    if (!isPro) {
      // Add watermark
      html = html.replace('</body>', '<div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.1; font-size: 48px; color: gray;">Vellon 2.0</div></body>');
    }

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(html);
    const pdfBuffer = await page.pdf({ format: 'A4' });
    await browser.close();

    return new Response(pdfBuffer as any, {
      headers: {
        'Content-Type': 'application/pdf',
      },
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}

function generateRoadmapHTML(roadmap: any[]): string {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Career Roadmap - Vellon 2.0</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
    .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
    .year-section { margin-bottom: 40px; padding: 20px; border-left: 4px solid #007bff; background: #f8f9fa; }
    .year-title { font-size: 24px; font-weight: bold; color: #007bff; margin-bottom: 15px; }
    .skills, .projects { margin-bottom: 15px; }
    .skills h4, .projects h4 { color: #333; margin-bottom: 8px; }
    .skill-item, .project-item { margin-left: 20px; margin-bottom: 5px; }
    .certifications { margin-top: 15px; }
    .certification { display: inline-block; background: #e9ecef; padding: 4px 8px; margin: 2px; border-radius: 4px; font-size: 12px; }
    .resources { margin-top: 15px; }
    .resource { color: #007bff; text-decoration: none; display: block; margin-bottom: 5px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Career Development Roadmap</h1>
    <p>Generated by Vellon 2.0 AI Career Assistant</p>
  </div>

  ${roadmap.map(item => `
    <div class="year-section">
      <div class="year-title">Year ${item.year}: ${item.target_role}</div>

      <div class="skills">
        <h4>Skills to Learn:</h4>
        ${item.skills_to_learn.map((skill: string) => `<div class="skill-item">• ${skill}</div>`).join('')}
      </div>

      <div class="projects">
        <h4>Suggested Projects:</h4>
        ${item.projects.map((project: string) => `<div class="project-item">• ${project}</div>`).join('')}
      </div>

      ${item.certifications ? `
        <div class="certifications">
          <h4>Recommended Certifications:</h4>
          ${item.certifications.map((cert: string) => `<span class="certification">${cert}</span>`).join('')}
        </div>
      ` : ''}

      ${item.resources ? `
        <div class="resources">
          <h4>Free Learning Resources:</h4>
          ${item.resources.map((resource: string) => `<a class="resource" href="${resource}">${resource}</a>`).join('')}
        </div>
      ` : ''}
    </div>
  `).join('')}

  <div style="text-align: center; margin-top: 50px; color: #666; font-size: 12px;">
    <p>This roadmap is AI-generated and should be adapted to your specific circumstances.</p>
  </div>
</body>
</html>
  `;

  return html;
}