import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import jsPDF from 'jspdf';

export async function POST(request: NextRequest) {
  try {
    const { client_id } = await request.json();

    if (!client_id) {
      return NextResponse.json({
        error: 'client_id is required'
      }, { status: 400 });
    }

    // Get complete client data
    const client = await prisma.client.findUnique({
      where: { id: client_id },
      include: {
        jobs: {
          include: {
            application: {
              include: {
                submission: true
              }
            }
          }
        }
      }
    });

    if (!client) {
      return NextResponse.json({
        error: 'Client not found'
      }, { status: 404 });
    }

    // Generate PDF report
    const doc = new jsPDF();
    let yPosition = 20;

    // Title
    doc.setFontSize(20);
    doc.text('Vellon Job Application Sprint Report', 20, yPosition);
    yPosition += 20;

    // Client Info
    doc.setFontSize(14);
    doc.text('Client Information:', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.text(`Name: ${client.name}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Email: ${client.email}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Location: ${client.location}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Target Roles: ${client.desiredTitles.join(', ')}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Industry: ${client.industry}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Experience: ${client.yearsExperience} years`, 20, yPosition);
    yPosition += 8;
    doc.text(`Work Preference: ${client.workPreference}`, 20, yPosition);
    yPosition += 15;

    // CV Section
    if (client.cvText) {
      doc.setFontSize(14);
      doc.text('Optimized CV:', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(9);
      const cvLines = doc.splitTextToSize(client.cvText.substring(0, 1000), 170);
      doc.text(cvLines, 20, yPosition);
      yPosition += cvLines.length * 5 + 10;
    }

    // LinkedIn Section
    doc.setFontSize(14);
    doc.text('LinkedIn Optimization:', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.text('Headline: [Generated during optimization process]', 20, yPosition);
    yPosition += 8;
    doc.text('Summary: [Generated during optimization process]', 20, yPosition);
    yPosition += 15;

    // Applications Summary
    doc.setFontSize(14);
    doc.text('Job Applications Submitted:', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    const submittedCount = client.jobs.filter((job: any) => job.application?.submission?.status === 'submitted').length;
    const totalCount = client.jobs.length;

    doc.text(`Total Applications Prepared: ${totalCount}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Applications Submitted: ${submittedCount}`, 20, yPosition);
    yPosition += 15;

    // Job Details
    doc.setFontSize(12);
    doc.text('Job Details:', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(9);
    for (const job of client.jobs.slice(0, 20)) { // Limit for PDF
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      doc.text(`${job.title} at ${job.company}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Location: ${job.location} | Match Score: ${job.matchScore}%`, 25, yPosition);
      yPosition += 6;
      doc.text(`Status: ${job.application?.submission?.status || 'Not submitted'}`, 25, yPosition);
      yPosition += 8;
    }

    // Next Steps
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(14);
    doc.text('Next Steps:', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    const nextSteps = [
      '1. Follow up on submitted applications within 1-2 weeks',
      '2. Continue applying to additional opportunities',
      '3. Update LinkedIn profile with optimized content',
      '4. Prepare for interviews with key achievements ready',
      '5. Consider premium outreach services for top companies'
    ];

    for (const step of nextSteps) {
      doc.text(step, 20, yPosition);
      yPosition += 8;
    }

    // Footer
    doc.setFontSize(8);
    doc.text('Generated by Vellon - The World\'s First AI-Powered Done-for-You Job Application Sprint Platform', 20, 280);

    // Convert to buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${client.name}_vellon_report.pdf"`
      }
    });

  } catch (error) {
    console.error('Generate Report API error:', error);
    return NextResponse.json({
      error: 'Internal server error during report generation'
    }, { status: 500 });
  }
}