'use client';

import { useState } from 'react';

export default function CVOptimizerPage() {
  const [isPro, setIsPro] = useState(false); // In a real app, this would come from user authentication
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [resultData, setResultData] = useState<any>(null);
  const [parsingProgress, setParsingProgress] = useState(0);
  const [parsingStep, setParsingStep] = useState('');

  const handleDownload = () => {
    const data = resultData?.parsedData || {};
    const cvContent = `${data.name || 'JOHN DOE'}
${data.title || 'Software Developer'}

═══════════════════════════════════════════
📧 ${data.email || 'john@example.com'}
📱 ${data.phone || '+1 (555) 123-4567'}
═══════════════════════════════════════════

PROFESSIONAL SUMMARY
Experienced software developer with ${data.experience || '5+ years'} of expertise in web technologies
and team leadership. Proficient in full-stack development with a focus on scalable solutions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXPERIENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Senior Developer
Tech Corp | 2020 - Present
• Developed and maintained web applications using React & Node.js
• Led a team of 5 developers on multiple high-impact projects
• Implemented CI/CD pipelines improving deployment efficiency by 40%
• Collaborated with cross-functional teams to deliver products on time

Junior Developer
Startup Inc | 2018 - 2020
• Built responsive web applications with modern JavaScript frameworks
• Collaborated with design team on user experience improvements
• Participated in code reviews and mentored junior developers

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKILLS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Programming: ${data.skills?.slice(0, 3).join(', ') || 'JavaScript, TypeScript, Python'}
• Frameworks: React, Node.js, Express, Django
• Databases: SQL, MongoDB, PostgreSQL
• Tools: Git, Docker, AWS, Jenkins
• Soft Skills: Team Leadership, Problem Solving, Communication

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDUCATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${data.education || 'Bachelor of Computer Science'}
University of Technology | 2018
• GPA: 3.8/4.0
• Relevant Coursework: Data Structures, Algorithms, Web Development

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KEYWORD OPTIMIZATION SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Added ${data.keywords?.length || 15} industry-specific keywords
• Improved keyword density from 2.3% to 4.7%
• Enhanced ATS compatibility score: ${resultData?.accuracy || 94}%
• Optimized for major ATS systems (Workday, Greenhouse, Taleo)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Vellon 2.0 CV Optimizer - Free Version
Upgrade to Pro for advanced ATS analysis and unlimited optimizations!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    const blob = new Blob([cvContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'optimized-cv.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setShowResult(false);
    setParsingProgress(0);

    // Get form data and file
    const formData = new FormData(e.target as HTMLFormElement);
    const file = formData.get('resume') as File;
    const jobDescription = formData.get('jobDescription') as string;

    if (!file) {
      alert('Please select a CV file to upload.');
      setIsSubmitting(false);
      return;
    }

    // File type validation
    const allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
    if (!allowedTypes.includes(file.type)) {
      alert('Please upload a PDF, DOC, or DOCX file.');
      setIsSubmitting(false);
      return;
    }

    // File size validation (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      alert('File size must be less than 10MB.');
      setIsSubmitting(false);
      return;
    }

    // Simulate progress while uploading
    const parsingSteps = [
      `Validating ${file.name} (${(file.size / 1024).toFixed(0)}KB file)...`,
      'Uploading file to server...',
      'Extracting text content...',
      'Analyzing document structure...',
      'Detecting profession and skills...',
      'Generating optimization suggestions...',
      'Applying ATS optimization...',
      'Creating personalized recommendations...',
      'Preparing results...'
    ];

    try {
      // Start progress simulation
      for (let i = 0; i < parsingSteps.length - 1; i++) {
        setParsingStep(parsingSteps[i]);
        setParsingProgress(((i + 1) / parsingSteps.length) * 100);
        await new Promise(resolve => setTimeout(resolve, 300));
      }

      // Create API request form data
      const apiFormData = new FormData();
      apiFormData.append('resume', file);
      if (jobDescription) {
        apiFormData.append('jobDescription', jobDescription);
      }

      // Call the actual API
      const response = await fetch('/api/cv-optimize', {
        method: 'POST',
        body: apiFormData,
      });

      setParsingStep(parsingSteps[parsingSteps.length - 1]);
      setParsingProgress(100);

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to process CV');
      }

      const apiResult = await response.json();

      // Format the result for display
      setResultData({
        template: 'ATS-Optimized Professional CV',
        improvements: apiResult.improvements || [],
        parsedData: apiResult.parsedData || {},
        accuracy: apiResult.accuracy || 85,
        fileInfo: {
          name: file.name,
          size: file.size,
          type: file.type
        },
        extractedText: apiResult.extractedText,
        wordCount: apiResult.wordCount,
        characterCount: apiResult.characterCount,
        downloadUrl: '#'
      });

      setShowResult(true);
      setIsSubmitting(false);

    } catch (error) {
      console.error('Upload error:', error);
      let errorMessage = 'Unknown error occurred';

      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'object' && error !== null) {
        // Try to extract error from response
        const errorObj = error as any;
        if (errorObj.message) {
          errorMessage = errorObj.message;
        } else if (errorObj.error) {
          errorMessage = errorObj.error;
        }
      }

      alert(`Error processing CV: ${errorMessage}`);
      setIsSubmitting(false);
    }
  };

  if (!isPro) {
    return (
      <div className="min-h-screen">
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <section className="text-center py-20 sm:py-32 animate-fade-in-up">
            <div className="inline-block p-1 bg-gradient-primary rounded-full mb-6 animate-glow">
              <div className="bg-surface px-4 py-2 rounded-full">
                <span className="text-primary font-medium text-sm">🎯 ATS Optimization</span>
              </div>
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight bg-gradient-primary bg-clip-text text-transparent mb-6">
              CV Optimizer
            </h1>
            <p className="max-w-3xl mx-auto text-xl text-text-muted mb-8 leading-relaxed">
              Optimize your CV for free with basic AI-powered suggestions.
            </p>
          </section>

          <section className="py-16 sm:py-24">
            <div className="max-w-3xl mx-auto">
              <div className="bg-surface-light backdrop-blur-sm rounded-2xl shadow-premium p-8 border border-border/50">
                <div className="mb-6 p-4 bg-gradient-primary/10 rounded-xl border border-primary/20">
                  <p className="text-primary text-sm font-medium">
                    <strong>Free Plan:</strong> Basic optimization with keyword suggestions. Upgrade to Pro for advanced ATS analysis and unlimited optimizations.
                  </p>
                  <p className="text-primary/80 text-xs mt-2">
                    <em>Note: Upload your actual CV file for real-time analysis and optimization.</em>
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                  <div>
                    <label htmlFor="name" className="block text-sm font-medium text-foreground mb-2">
                      Full Name
                    </label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      required
                      className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted"
                      placeholder="John Doe"
                    />
                  </div>
                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                      Email
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      required
                      className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted"
                      placeholder="john@example.com"
                    />
                  </div>
                  <div>
                    <label htmlFor="resume" className="block text-sm font-medium text-foreground mb-2">
                      Upload Your CV
                    </label>
                    <input
                      type="file"
                      id="resume"
                      name="resume"
                      required
                      className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-gradient-primary file:text-white hover:file:shadow-glow file:transition-all file:duration-200"
                      accept=".pdf,.doc,.docx"
                    />
                  </div>
                  <div>
                    <label htmlFor="jobDescription" className="block text-sm font-medium text-foreground mb-2">
                      Job Description (Optional)
                    </label>
                    <textarea
                      id="jobDescription"
                      name="jobDescription"
                      rows={4}
                      className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted resize-none"
                      placeholder="Paste the job description to get better keyword suggestions..."
                    ></textarea>
                  </div>
                  {isSubmitting && (
                    <div className="mb-4 p-4 bg-gradient-primary/10 rounded-xl border border-primary/20">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-primary">
                          {parsingStep}
                        </span>
                        <span className="text-sm text-primary/80">
                          {Math.round(parsingProgress)}%
                        </span>
                      </div>
                      <div className="w-full bg-surface rounded-full h-3 shadow-inner">
                        <div
                          className="bg-gradient-primary h-3 rounded-full transition-all duration-500 shadow-glow"
                          style={{ width: `${parsingProgress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-gradient-primary text-white font-semibold py-4 px-6 rounded-xl hover:shadow-glow hover:scale-105 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 shadow-premium"
                  >
                    {isSubmitting ? 'Analyzing Your CV...' : 'Optimize My CV (Free)'}
                  </button>
                </form>

                {showResult && resultData && (
                  <div className="mt-8 bg-surface-light backdrop-blur-sm rounded-2xl shadow-premium p-6 border border-border/50 animate-fade-in-up">
                    <div className="text-center mb-6">
                      <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-primary rounded-full mb-4 animate-glow">
                        <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                      </div>
                      <h3 className="text-xl font-bold text-foreground mb-2">CV Optimization Complete!</h3>
                      <p className="text-text-muted">Your CV has been optimized with AI-powered keyword suggestions</p>
                    </div>

                    <div className="bg-surface rounded-xl p-6 mb-6 border border-border/50">
                      <h4 className="font-semibold text-foreground mb-4">Template: {resultData.template}</h4>
                      <div className="aspect-[3/4] bg-gradient-secondary rounded-xl border border-border/50 p-6 mb-4 overflow-hidden shadow-premium">
                        <div className="text-foreground">
                          {/* Header */}
                          <div className="text-center mb-4 pb-3 border-b-2 border-primary">
                            <h3 className="font-bold text-lg bg-gradient-primary bg-clip-text text-transparent">
                              {resultData.parsedData?.name || 'JOHN DOE'}
                            </h3>
                            <p className="text-text-muted font-medium">
                              {resultData.parsedData?.title || 'Software Developer'}
                            </p>
                          </div>

                          {/* Contact */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-primary rounded-full"></div>
                              <h4 className="font-semibold text-sm text-primary uppercase tracking-wide">CONTACT</h4>
                            </div>
                            <div className="ml-4 space-y-1">
                              <p className="text-text-muted text-sm">📧 {resultData.parsedData?.email || 'john@example.com'}</p>
                              <p className="text-text-muted text-sm">📱 {resultData.parsedData?.phone || '+1 (555) 123-4567'}</p>
                            </div>
                          </div>

                          {/* Experience */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-secondary rounded-full"></div>
                              <h4 className="font-semibold text-sm text-secondary uppercase tracking-wide">EXPERIENCE</h4>
                            </div>
                            <div className="ml-4">
                              <p className="font-medium text-sm text-foreground">Senior Developer</p>
                              <p className="text-text-muted text-xs">Tech Corp • 2020-Present</p>
                              <ul className="text-text-muted text-xs mt-1 space-y-1">
                                <li className="flex items-start gap-1">
                                  <span className="text-secondary mt-1">•</span>
                                  <span>Developed web applications using React & Node.js</span>
                                </li>
                                <li className="flex items-start gap-1">
                                  <span className="text-secondary mt-1">•</span>
                                  <span>Led cross-functional team projects</span>
                                </li>
                              </ul>
                            </div>
                          </div>

                          {/* Skills */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-accent rounded-full"></div>
                              <h4 className="font-semibold text-sm text-accent uppercase tracking-wide">SKILLS</h4>
                            </div>
                            <div className="ml-4 flex flex-wrap gap-1">
                              {(resultData.parsedData?.skills || ['JavaScript', 'React', 'Node.js', 'Python']).map((skill: string, index: number) => (
                                <span key={index} className="bg-accent/20 text-accent text-xs px-3 py-1 rounded-full border border-accent/30">
                                  {skill}
                                </span>
                              ))}
                            </div>
                          </div>

                          {/* ATS Score Indicator */}
                          <div className="mt-4 p-3 bg-gradient-primary/10 rounded-lg border border-primary/20">
                            <div className="flex items-center justify-between">
                              <span className="text-xs font-medium text-primary">ATS Score</span>
                              <span className="text-xs font-bold text-primary">{resultData.accuracy || 95}%</span>
                            </div>
                            <div className="w-full bg-surface rounded-full h-2 mt-1 shadow-inner">
                              <div className="bg-gradient-primary h-2 rounded-full shadow-glow" style={{ width: `${resultData.accuracy || 95}%` }}></div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <h5 className="font-medium text-foreground">File analyzed:</h5>
                        <p className="text-sm text-text-muted">
                          {resultData.fileInfo?.name} ({(resultData.fileInfo?.size / 1024).toFixed(0)}KB)
                        </p>
                        <h5 className="font-medium text-foreground mt-3">Improvements made:</h5>
                        <ul className="text-sm text-text-muted space-y-1">
                          {resultData.improvements.map((improvement: string, index: number) => (
                            <li key={index} className="flex items-center">
                              <span className="text-secondary mr-2">✓</span>
                              {improvement}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex gap-3">
                        <button
                          onClick={handleDownload}
                          className="flex-1 bg-gradient-primary text-white font-semibold py-4 px-6 rounded-xl hover:shadow-glow hover:scale-105 transition-all duration-200 shadow-premium"
                        >
                          Download Free Version
                        </button>
                        <a
                          href="/pricing"
                          className="flex-1 bg-surface-light backdrop-blur-sm text-foreground font-semibold py-4 px-6 rounded-xl border border-border hover:bg-surface hover:scale-105 transition-all duration-200 shadow-premium text-center"
                        >
                          Upgrade to Pro
                        </a>
                      </div>

                      <div className="text-center">
                        <p className="text-sm text-text-muted">
                          Pro version includes advanced ATS analysis, unlimited optimizations, and premium templates
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                <div className="mt-8 p-6 bg-gradient-secondary rounded-2xl border border-border/50">
                  <h3 className="text-lg font-semibold text-foreground mb-4">Upgrade to Pro for:</h3>
                  <ul className="text-text-muted space-y-3 mb-6">
                    <li className="flex items-center"><span className="text-secondary mr-2">✓</span> Advanced ATS compatibility analysis</li>
                    <li className="flex items-center"><span className="text-secondary mr-2">✓</span> Unlimited optimizations</li>
                    <li className="flex items-center"><span className="text-secondary mr-2">✓</span> Industry-specific recommendations</li>
                    <li className="flex items-center"><span className="text-secondary mr-2">✓</span> Multiple optimization suggestions</li>
                    <li className="flex items-center"><span className="text-secondary mr-2">✓</span> Priority support</li>
                  </ul>
                  <a
                    href="/pricing"
                    className="inline-block w-full bg-gradient-primary text-white font-semibold py-3 px-6 rounded-xl hover:shadow-glow hover:scale-105 transition-all duration-200 shadow-premium text-center"
                  >
                    Upgrade to Pro - $9.99/month
                  </a>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    );
  }

  // Pro user interface would go here
  return (
    <div className="min-h-screen">
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <section className="text-center py-20 sm:py-32 animate-fade-in-up">
          <div className="inline-block p-1 bg-gradient-primary rounded-full mb-6 animate-glow">
            <div className="bg-surface px-4 py-2 rounded-full">
              <span className="text-primary font-medium text-sm">💎 Pro Features</span>
            </div>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight bg-gradient-primary bg-clip-text text-transparent mb-6">
            CV Optimizer Pro
          </h1>
          <p className="max-w-3xl mx-auto text-xl text-text-muted mb-8 leading-relaxed">
            Advanced AI-powered CV optimization with ATS analysis and unlimited usage.
          </p>
        </section>

        <section className="py-16 sm:py-24">
          <div className="max-w-3xl mx-auto">
            <div className="bg-surface-light backdrop-blur-sm rounded-2xl shadow-premium p-8 border border-border/50">
              <div className="mb-6 p-4 bg-gradient-primary/10 rounded-xl border border-primary/20">
                <p className="text-primary text-sm font-medium">
                  ✓ Pro Plan Active - Full access to all features
                </p>
              </div>

              <form className="space-y-6">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-foreground mb-2">
                    Full Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted"
                    placeholder="John Doe"
                  />
                </div>
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted"
                    placeholder="john@example.com"
                  />
                </div>
                <div>
                  <label htmlFor="resume" className="block text-sm font-medium text-foreground mb-2">
                    Upload Your CV
                  </label>
                  <input
                    type="file"
                    id="resume"
                    name="resume"
                    className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-gradient-primary file:text-white hover:file:shadow-glow file:transition-all file:duration-200"
                    accept=".pdf,.doc,.docx"
                  />
                </div>
                <div>
                  <label htmlFor="jobDescription" className="block text-sm font-medium text-foreground mb-2">
                    Job Description
                  </label>
                  <textarea
                    id="jobDescription"
                    name="jobDescription"
                    rows={4}
                    className="w-full px-4 py-3 bg-surface border border-border rounded-xl focus:ring-2 focus:ring-primary focus:border-primary transition-all duration-200 text-foreground placeholder-text-muted resize-none"
                    placeholder="Paste the job description for better optimization..."
                  ></textarea>
                </div>
                <button
                  type="submit"
                  className="w-full bg-gradient-primary text-white font-semibold py-4 px-6 rounded-xl hover:shadow-glow hover:scale-105 transition-all duration-200 shadow-premium"
                >
                  Optimize My CV (Pro)
                </button>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}