'use client';

import { useState } from 'react';

export default function CVOptimizerPage() {
  const [isPro, setIsPro] = useState(false); // In a real app, this would come from user authentication
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const [resultData, setResultData] = useState<any>(null);
  const [parsingProgress, setParsingProgress] = useState(0);
  const [parsingStep, setParsingStep] = useState('');

  const handleDownload = () => {
    const data = resultData?.parsedData || {};
    const cvContent = `${data.name || 'JOHN DOE'}
${data.title || 'Software Developer'}

═══════════════════════════════════════════
📧 ${data.email || 'john@example.com'}
📱 ${data.phone || '+1 (555) 123-4567'}
═══════════════════════════════════════════

PROFESSIONAL SUMMARY
Experienced software developer with ${data.experience || '5+ years'} of expertise in web technologies
and team leadership. Proficient in full-stack development with a focus on scalable solutions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXPERIENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Senior Developer
Tech Corp | 2020 - Present
• Developed and maintained web applications using React & Node.js
• Led a team of 5 developers on multiple high-impact projects
• Implemented CI/CD pipelines improving deployment efficiency by 40%
• Collaborated with cross-functional teams to deliver products on time

Junior Developer
Startup Inc | 2018 - 2020
• Built responsive web applications with modern JavaScript frameworks
• Collaborated with design team on user experience improvements
• Participated in code reviews and mentored junior developers

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKILLS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Programming: ${data.skills?.slice(0, 3).join(', ') || 'JavaScript, TypeScript, Python'}
• Frameworks: React, Node.js, Express, Django
• Databases: SQL, MongoDB, PostgreSQL
• Tools: Git, Docker, AWS, Jenkins
• Soft Skills: Team Leadership, Problem Solving, Communication

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDUCATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${data.education || 'Bachelor of Computer Science'}
University of Technology | 2018
• GPA: 3.8/4.0
• Relevant Coursework: Data Structures, Algorithms, Web Development

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KEYWORD OPTIMIZATION SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Added ${data.keywords?.length || 15} industry-specific keywords
• Improved keyword density from 2.3% to 4.7%
• Enhanced ATS compatibility score: ${resultData?.accuracy || 94}%
• Optimized for major ATS systems (Workday, Greenhouse, Taleo)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Vellon 2.0 CV Optimizer - Free Version
Upgrade to Pro for advanced ATS analysis and unlimited optimizations!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    const blob = new Blob([cvContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'optimized-cv.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setShowResult(false);
    setParsingProgress(0);

    // Get form data and file
    const formData = new FormData(e.target as HTMLFormElement);
    const file = formData.get('resume') as File;
    const jobDescription = formData.get('jobDescription') as string;

    if (!file) {
      alert('Please select a CV file to upload.');
      setIsSubmitting(false);
      return;
    }

    // File type validation
    const allowedTypes = ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
    if (!allowedTypes.includes(file.type)) {
      alert('Please upload a PDF, DOC, or DOCX file.');
      setIsSubmitting(false);
      return;
    }

    // File size validation (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      alert('File size must be less than 10MB.');
      setIsSubmitting(false);
      return;
    }

    // File property analysis simulation (frontend limitation: cannot parse PDF content)
    const parsingSteps = [
      `Validating ${file.name} (${(file.size / 1024).toFixed(0)}KB file)...`,
      'Analyzing filename for profession keywords...',
      'Extracting potential name from file naming patterns...',
      'Estimating experience level from file size...',
      'Mapping profession to relevant skills database...',
      'Generating profession-specific keyword suggestions...',
      'Applying ATS optimization patterns...',
      jobDescription ? 'Incorporating job description keywords...' : 'Using industry-standard keywords...',
      'Creating personalized improvement recommendations...',
      'Preparing downloadable optimized CV template...',
      'Finalizing results...'
    ];

    for (let i = 0; i < parsingSteps.length; i++) {
      setParsingStep(parsingSteps[i]);
      setParsingProgress(((i + 1) / parsingSteps.length) * 100);
      await new Promise(resolve => setTimeout(resolve, 500));
    }

    setIsSubmitting(false);

    // Simulate parsing based on actual file properties and generate realistic data
    const fileName = file.name.toLowerCase();
    const fileSize = file.size;

    // Advanced parsing logic based on file analysis
    const analyzeFileName = (fileName: string) => {
      const lowerName = fileName.toLowerCase();

      // Profession detection with priority
      if (lowerName.includes('software') || lowerName.includes('developer') || lowerName.includes('engineer') || lowerName.includes('programmer')) {
        return {
          profession: 'Software Developer',
          skills: ['JavaScript', 'React', 'Node.js', 'Python', 'TypeScript', 'AWS', 'Docker', 'Git'],
          keywords: ['JavaScript', 'React', 'Node.js', 'Full-Stack Development', 'API Design', 'Database Management', 'Agile', 'Scrum']
        };
      }
      if (lowerName.includes('designer') || lowerName.includes('ux') || lowerName.includes('ui')) {
        return {
          profession: 'UX/UI Designer',
          skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research', 'Wireframing', 'Usability Testing'],
          keywords: ['UI/UX Design', 'User Experience', 'Prototyping', 'Wireframing', 'Design Systems', 'Figma', 'Adobe Creative Suite']
        };
      }
      if (lowerName.includes('manager') || lowerName.includes('lead') || lowerName.includes('director')) {
        return {
          profession: 'Project Manager',
          skills: ['Project Management', 'Agile', 'Scrum', 'Leadership', 'Communication', 'Risk Management'],
          keywords: ['Project Management', 'Agile Methodology', 'Team Leadership', 'Stakeholder Management', 'Risk Assessment']
        };
      }
      if (lowerName.includes('analyst') || lowerName.includes('data')) {
        return {
          profession: 'Data Analyst',
          skills: ['SQL', 'Python', 'Excel', 'Tableau', 'Power BI', 'Statistics', 'Data Visualization'],
          keywords: ['Data Analysis', 'SQL', 'Python', 'Data Visualization', 'Statistical Analysis', 'Business Intelligence']
        };
      }
      if (lowerName.includes('marketing') || lowerName.includes('market')) {
        return {
          profession: 'Marketing Specialist',
          skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Social Media', 'Google Analytics', 'Email Marketing'],
          keywords: ['Digital Marketing', 'SEO', 'Content Strategy', 'Social Media Marketing', 'Google Analytics', 'Email Campaigns']
        };
      }

      // Default professional profile
      return {
        profession: 'Professional',
        skills: ['Communication', 'Leadership', 'Problem Solving', 'Team Collaboration', 'Project Management'],
        keywords: ['Professional Development', 'Leadership', 'Communication', 'Team Collaboration', 'Problem Solving']
      };
    };

    const professionData = analyzeFileName(fileName);

    // Experience level based on file size and naming patterns
    const getExperienceLevel = (fileSize: number, fileName: string) => {
      const lowerName = fileName.toLowerCase();
      if (lowerName.includes('senior') || lowerName.includes('lead') || lowerName.includes('principal')) return '7+ years';
      if (lowerName.includes('mid') || fileSize > 600000) return '4-6 years';
      if (fileSize > 400000) return '3-5 years';
      if (fileSize > 200000) return '2-4 years';
      return '1-3 years';
    };

    // Enhanced name extraction with better patterns
    const extractNameFromFile = (fileName: string) => {
      // Remove extension and common CV words
      let cleanName = fileName
        .replace(/\.(pdf|doc|docx)$/i, '')
        .replace(/\b(cv|resume|curriculum| vitae)\b/gi, '')
        .replace(/[_-]/g, ' ')
        .trim();

      // Handle different naming patterns
      if (cleanName.includes(' ')) {
        // Already has spaces, assume it's "First Last"
        return cleanName.split(' ').slice(0, 2).map(word =>
          word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
        ).join(' ');
      } else if (cleanName.length > 6) {
        // Single word, try to split camelCase or find name-like patterns
        const camelCaseMatch = cleanName.match(/([a-z]+)([A-Z][a-z]+)/);
        if (camelCaseMatch) {
          return `${camelCaseMatch[1].charAt(0).toUpperCase()}${camelCaseMatch[1].slice(1)} ${camelCaseMatch[2]}`;
        }
      }

      // Fallback to generic name
      return 'Alex Johnson';
    };

    const extractedData = {
      name: extractNameFromFile(fileName),
      title: professionData.profession,
      email: `${extractNameFromFile(fileName).toLowerCase().replace(/\s+/g, '.')}@email.com`,
      phone: '+1 (555) 123-4567',
      experience: getExperienceLevel(fileSize, fileName),
      skills: professionData.skills,
      education: professionData.profession.includes('Software') ? 'Bachelor of Computer Science' :
                 professionData.profession.includes('Design') ? 'Bachelor of Fine Arts' :
                 professionData.profession.includes('Data') ? 'Bachelor of Statistics' :
                 'Bachelor of Business Administration',
      keywords: jobDescription ? professionData.keywords : professionData.keywords.slice(0, 5)
    };

    // Calculate realistic improvements based on file analysis
    const baseImprovements = [
      `Analyzed ${file.name} (${(file.size / 1024).toFixed(0)}KB)`,
      `Added ${extractedData.keywords.length} relevant keywords`,
      'Enhanced section hierarchy for ATS parsing',
      'Optimized contact information formatting',
      'Improved keyword density optimization'
    ];

    if (jobDescription) {
      baseImprovements.push('Tailored content to match job description');
      baseImprovements.push('Increased job-specific keyword relevance');
    }

    setResultData({
      template: 'ATS-Optimized Professional CV',
      improvements: baseImprovements,
      parsedData: extractedData,
      accuracy: Math.floor(85 + Math.random() * 10), // 85-95% accuracy
      fileInfo: {
        name: file.name,
        size: file.size,
        type: file.type
      },
      downloadUrl: '#'
    });
    setShowResult(true);
  };

  if (!isPro) {
    return (
      <div className="bg-zinc-50 dark:bg-black">
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <section className="text-center py-20 sm:py-32">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white mb-6">
              CV Optimizer
            </h1>
            <p className="max-w-3xl mx-auto text-xl text-gray-600 dark:text-gray-300 mb-8">
              Optimize your CV for free with basic AI-powered suggestions.
            </p>
          </section>

          <section className="py-16 sm:py-24">
            <div className="max-w-3xl mx-auto">
              <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
                <div className="mb-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                  <p className="text-blue-800 dark:text-blue-200 text-sm">
                    <strong>Free Plan:</strong> Basic optimization with keyword suggestions. Upgrade to Pro for advanced ATS analysis and unlimited optimizations.
                  </p>
                  <p className="text-blue-700 dark:text-blue-300 text-xs mt-2">
                    <em>Note: This demo analyzes file properties and simulates parsing. Real PDF content parsing requires server-side processing.</em>
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-6">
                  <div>
                    <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Full Name
                    </label>
                    <input
                      type="text"
                      id="name"
                      name="name"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="John Doe"
                    />
                  </div>
                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Email
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="john@example.com"
                    />
                  </div>
                  <div>
                    <label htmlFor="resume" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Upload Your CV
                    </label>
                    <input
                      type="file"
                      id="resume"
                      name="resume"
                      required
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      accept=".pdf,.doc,.docx"
                    />
                  </div>
                  <div>
                    <label htmlFor="jobDescription" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Job Description (Optional)
                    </label>
                    <textarea
                      id="jobDescription"
                      name="jobDescription"
                      rows={4}
                      className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                      placeholder="Paste the job description to get better keyword suggestions..."
                    ></textarea>
                  </div>
                  {isSubmitting && (
                    <div className="mb-4 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-blue-800 dark:text-blue-200">
                          {parsingStep}
                        </span>
                        <span className="text-sm text-blue-600 dark:text-blue-300">
                          {Math.round(parsingProgress)}%
                        </span>
                      </div>
                      <div className="w-full bg-blue-200 dark:bg-blue-800 rounded-full h-2">
                        <div
                          className="bg-blue-600 dark:bg-blue-400 h-2 rounded-full transition-all duration-300"
                          style={{ width: `${parsingProgress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className="w-full bg-black dark:bg-white text-white dark:text-black py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isSubmitting ? 'Analyzing Your CV...' : 'Optimize My CV (Free)'}
                  </button>
                </form>

                {showResult && resultData && (
                  <div className="mt-8 bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 border border-gray-200 dark:border-gray-700">
                    <div className="text-center mb-6">
                      <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 dark:bg-green-900/20 rounded-full mb-4">
                        <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                      </div>
                      <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">CV Optimization Complete!</h3>
                      <p className="text-gray-600 dark:text-gray-300">Your CV has been optimized with basic keyword suggestions</p>
                    </div>

                    <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 mb-6">
                      <h4 className="font-semibold text-gray-900 dark:text-white mb-3">Template: {resultData.template}</h4>
                      <div className="aspect-[3/4] bg-gradient-to-br from-slate-50 to-blue-50 dark:from-gray-800 dark:to-gray-700 rounded-lg border border-gray-200 dark:border-gray-600 p-6 mb-4 overflow-hidden shadow-sm">
                        <div className="text-gray-900 dark:text-white">
                          {/* Header */}
                          <div className="text-center mb-4 pb-3 border-b-2 border-blue-500">
                            <h3 className="font-bold text-lg text-blue-900 dark:text-blue-200">
                              {resultData.parsedData?.name || 'JOHN DOE'}
                            </h3>
                            <p className="text-gray-600 dark:text-gray-300 font-medium">
                              {resultData.parsedData?.title || 'Software Developer'}
                            </p>
                          </div>

                          {/* Contact */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-blue-800 dark:text-blue-300">CONTACT</h4>
                            </div>
                            <div className="ml-4 space-y-1">
                              <p className="text-gray-700 dark:text-gray-200 text-sm">📧 john@example.com</p>
                              <p className="text-gray-700 dark:text-gray-200 text-sm">📱 +1 (555) 123-4567</p>
                            </div>
                          </div>

                          {/* Experience */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-green-800 dark:text-green-300">EXPERIENCE</h4>
                            </div>
                            <div className="ml-4">
                              <p className="font-medium text-sm text-gray-900 dark:text-white">Senior Developer</p>
                              <p className="text-gray-600 dark:text-gray-300 text-xs">Tech Corp • 2020-Present</p>
                              <ul className="text-gray-700 dark:text-gray-200 text-xs mt-1 space-y-1">
                                <li className="flex items-start gap-1">
                                  <span className="text-green-500 mt-1">•</span>
                                  <span>Developed web applications using React & Node.js</span>
                                </li>
                                <li className="flex items-start gap-1">
                                  <span className="text-green-500 mt-1">•</span>
                                  <span>Led cross-functional team projects</span>
                                </li>
                              </ul>
                            </div>
                          </div>

                          {/* Skills */}
                          <div className="mb-4">
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-2 h-2 bg-purple-500 rounded-full"></div>
                              <h4 className="font-semibold text-sm text-purple-800 dark:text-purple-300">SKILLS</h4>
                            </div>
                            <div className="ml-4 flex flex-wrap gap-1">
                              {(resultData.parsedData?.skills || ['JavaScript', 'React', 'Node.js', 'Python']).map((skill: string, index: number) => (
                                <span key={index} className="bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-200 text-xs px-2 py-1 rounded-full">
                                  {skill}
                                </span>
                              ))}
                            </div>
                          </div>

                          {/* ATS Score Indicator */}
                          <div className="mt-4 p-2 bg-green-50 dark:bg-green-900/20 rounded border border-green-200 dark:border-green-800">
                            <div className="flex items-center justify-between">
                              <span className="text-xs font-medium text-green-800 dark:text-green-200">ATS Score</span>
                              <span className="text-xs font-bold text-green-800 dark:text-green-200">95%</span>
                            </div>
                            <div className="w-full bg-green-200 dark:bg-green-800 rounded-full h-1 mt-1">
                              <div className="bg-green-600 dark:bg-green-400 h-1 rounded-full" style={{ width: '95%' }}></div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <h5 className="font-medium text-gray-900 dark:text-white">File analyzed:</h5>
                        <p className="text-sm text-gray-600 dark:text-gray-300">
                          {resultData.fileInfo?.name} ({(resultData.fileInfo?.size / 1024).toFixed(0)}KB)
                        </p>
                        <h5 className="font-medium text-gray-900 dark:text-white mt-3">Improvements made:</h5>
                        <ul className="text-sm text-gray-600 dark:text-gray-300 space-y-1">
                          {resultData.improvements.map((improvement: string, index: number) => (
                            <li key={index} className="flex items-center">
                              <span className="text-green-500 mr-2">✓</span>
                              {improvement}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex gap-3">
                        <button
                          onClick={handleDownload}
                          className="flex-1 bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-medium py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors"
                        >
                          Download Free Version
                        </button>
                        <a
                          href="/pricing"
                          className="flex-1 bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-medium py-3 px-4 rounded-lg border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-center"
                        >
                          Upgrade to Pro
                        </a>
                      </div>

                      <div className="text-center">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Pro version includes advanced ATS analysis, unlimited optimizations, and premium templates
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                <div className="mt-8 p-6 bg-gradient-to-r from-gray-50 to-gray-100 dark:from-gray-800 dark:to-gray-700 rounded-lg">
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">Upgrade to Pro for:</h3>
                  <ul className="text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                    <li>✓ Advanced ATS compatibility analysis</li>
                    <li>✓ Unlimited optimizations</li>
                    <li>✓ Industry-specific recommendations</li>
                    <li>✓ Multiple optimization suggestions</li>
                    <li>✓ Priority support</li>
                  </ul>
                  <a
                    href="/pricing"
                    className="inline-block bg-gray-900 dark:bg-white text-white dark:text-gray-900 font-medium py-2 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors text-sm"
                  >
                    Upgrade to Pro - $9.99/month
                  </a>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    );
  }

  // Pro user interface would go here
  return (
    <div className="bg-zinc-50 dark:bg-black">
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <section className="text-center py-20 sm:py-32">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 dark:text-white mb-6">
            CV Optimizer Pro
          </h1>
          <p className="max-w-3xl mx-auto text-xl text-gray-600 dark:text-gray-300 mb-8">
            Advanced AI-powered CV optimization with ATS analysis and unlimited usage.
          </p>
        </section>

        <section className="py-16 sm:py-24">
          <div className="max-w-3xl mx-auto">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
              <div className="mb-6 p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
                <p className="text-green-800 dark:text-green-200 text-sm font-medium">
                  ✓ Pro Plan Active - Full access to all features
                </p>
              </div>

              <form className="space-y-6">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Full Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    placeholder="John Doe"
                  />
                </div>
                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Email
                  </label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    placeholder="john@example.com"
                  />
                </div>
                <div>
                  <label htmlFor="resume" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Upload Your CV
                  </label>
                  <input
                    type="file"
                    id="resume"
                    name="resume"
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    accept=".pdf,.doc,.docx"
                  />
                </div>
                <div>
                  <label htmlFor="jobDescription" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Job Description
                  </label>
                  <textarea
                    id="jobDescription"
                    name="jobDescription"
                    rows={4}
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent dark:bg-gray-700 dark:text-white"
                    placeholder="Paste the job description for better optimization..."
                  ></textarea>
                </div>
                <button
                  type="submit"
                  className="w-full bg-black dark:bg-white text-white dark:text-black py-3 px-4 rounded-lg hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors font-medium"
                >
                  Optimize My CV (Pro)
                </button>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}